Repository nordugrid/arctestsite-hackathon-slurm-el7-arc7, pull requests merged in 2022-09, with the labels that each got.

#1 testing arc.conf change via PR
  arc.conf
Labels: moved_gitlab

#2 arc conf change in github
  arc.conf
Labels: moved_gitlab

#3 add authtokens block
  arc.conf
Labels: moved_gitlab

#9 test9
  arc.conf
Labels: webhook:moved_gitlab

#11 Add LIGO issuer to arc.conf
  arc.conf
Labels: conf:arc, webhook:moved_gitlab

#12 Switch to the issuer used by others
  arc.conf
Labels: conf:arc, webhook:moved_gitlab

#13 publicinfo
  arc.conf
Labels: webhook:moved_gitlab

#14 Update arc.conf
  arc.conf
Labels: webhook:moved_gitlab

#16 default hostcert
  arc.conf
Labels: webhook:moved_gitlab

#15 Config for WLCG IAM and EGI Check-In
  arc.conf
Labels: webhook:moved_gitlab

#10 Add indigo-iam token issuer authtoken block
  arc.conf
Labels: conf:arc, webhook:moved_gitlab

#17 removing duplicates
  arc.conf
Labels: webhook:moved_gitlab

#18 add Andrea Manzi mapping via EGI Check-in
  arc.conf
Labels: conf:arc, webhook:moved_gitlab

#21 Just a cleanup of WLCG IAM configuration
  arc.conf
  nordugrid-arc-arcctl-20220915100552-1.el7.x86_64.rpm
  nordugrid-arc-arcctl-service-20220915100552-1.el7.x86_64.rpm
  nordugrid-arc-client-20220915100552-1.el7.x86_64.rpm
  nordugrid-arc-plugins-arcrest-20220915100552-1.el7.x86_64.rpm
Labels: conf:arc, webhook:moved_gitlab
